### ISSUE TITLE
Spatial Overlap

### ISSUE THREAD

**Issue by saraorofino** [tcarleton/climate-aggregate#2]
Hi @tcarleton I'm working on the building out the initial raster/polygon overlap and had some questions: 

- Is the output of this step ideally a raster or can it be a data.table? And do we simply want the overlap or do we also want to include a weight based on the fraction of overlap? Following the Schlenker example I've created a data.table of 'geoweights' with the polygon id, raster cell id, and the coverage fraction (fraction of the raster cell covered by the polygon) but I wanted to double check that this format is okay and we don't need it to be a raster. 
- The Era5 example data I got from Anna has 0-360 longitude (and I think all era5 will be the same), do you have a preference on the output of this step being 0-360 vs. -180 to 180? The lats are also -90.125 to 90.125 and I wasn't sure if we needed to adjust the center of the grid so it doesn't fall outside of -90/90. 
- Do we want/need to normalize the weights by the administrative boundary level? The Schlenker example normalizes the coverage fraction by county (i.e. group by county and weight / sum(weight)) but I didn't know if that was necessary for our case or not

**Comment by tcarleton** [comment]
Hi @saraorofino!

- `data.table` works great, no need to create a raster. your solution sounds 💯 
- I don't have a preference on longitude, we just need to make sure we are consistent -- can you build in a check that confirms the polygon lon range matches the climate raster lon range and then an error gets thrown if that violates?
- I feel like that normalization is automatic in `extract()` but maybe it's not in `exactextract()`? We definitely want weights to sum to 1 within a county/polygon

**Comment by saraorofino** [comment]
Sounds great thanks @tcarleton . 

- For longitude: I have it set to adjust one to the other, but I'll add in a consistency check/error message. 
- Normalization does not appear to be automatic in `exactextract()` but I have code in there to normalize by the input polygons (it's currently a T/F user defined option but I will just have it always normalize). 

I will have these done tomorrow and then I have just a couple minor questions to clarify in the meeting

**Comment by tcarleton** [comment]
Ok cool would love to have a look at your code @saraorofino -- I don't see a branch from you?

**Comment by saraorofino** [comment]
@tcarleton  yes, sorry I just pushed my branch and you should see the script in the `code` folder now

**Comment by saraorofino** [comment]
Hi @tcarleton - just pushed some changes to the code. Summarized below: 

- New input: `data_source` replaces the `climate_param` and `year`.  Sorry I haven't gotten the `data/raw/demo/` folder setup on the pod yet so it's still hard coding with a demo file on my desktop. Ideally in this folder we'll have just a single day's file for a few different common climate data sources that we can include as options. 
- Lines 22-31: normalizes the `data_source` input to all lowercase with no spaces (so you can input ERA 5, ERA5, Era5 etc. and they'll all convert to `era5` to link correctly with the datafile) which is how I want to setup the file names (e.g. `era5_demo.nc`, `prism_demo.nc` etc). It will throw an error if the input is not one of the climate data sources we have a file for. As of now it only accepts `era5` (and variations of that) but we can expand later. 
- Line 52: calculate the area of the raster cells in km2. This keeps throwing a warning `raster has a longitude/latitude crs, but coordinates do not match that` and I'm not sure what to do about that but it seems to still be working fine. I'm including a screenshot of `plot(clim_area_rast)` below which should be showing the values for grid cell area in km2 to make sure that this seems reasonable. To my knowledge 0.25 degrees near the equator is maybe like 27-28 km so something in the upper 700s makes sense to me (the raster max is 769.317) but it would be great to get confirmation on this. 
- Line 99: the `values` column pulled in by `exact_extract` is now pulling the area in km2, which I'm renaming in this line for clarity 
- Line 100: `w_geo` is now using the `coverage_fraction` * `cell_area_km2` 
- Lines 108-114: checking that the sum of `w_geo` for all polygon ids = 1. If not it will error with which polygon doesn't sum to 1 and if there's no error than all polygon weights summed to 1. 
- Output: the output still has three columns; `gridNumber`,  `poly_id`, `w_geo`. I double checked and the max of w_geo = 1  and the min is near 0 but not exact which all makes sense to me.  

Screenshot of the raster of cell areas in km2: 
<img width="1108" alt="raster_area_km2" src="https://user-images.githubusercontent.com/43861300/152626036-4ad9e13a-70db-4ceb-b138-1e7edd181111.png">
